apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
        - name: gcp-devops-gke
          image: gcr.io/decisive-coder-384407/gcpdevops-dev:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service-dev"
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports: 
   - protocol: "TCP"
     port: 80
     targetPort: 4000
  selector:
    app: "gcp"
  type: "LoadBalancer"